import './globals.css'
import { Inter } from 'next/font/google'
import Providers from "@/utils/provider";
import React from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Rick And Morty',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} + bg-gray-900`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
